job-manager:
  address: "192.168.118.202"
  port: 1235
  scriptRoot: '/data/www_dev/cstb/lib/cstb2-server/src/scripts'

db:
  couchDB:
    host: 'arwen-cdb.ibcp.fr'
    port: 5984
    user: 'cstb_agent'
    password: '8n9m8n9m4zY2kZtePvP'
    
    maxi_tree:
      database: 'tree'
    taxon:
      name: 'taxon_db'
    genome:
      name: 'genome_db'

  motif-broker:
    host: 'localhost'
    port: 0000

allGenomes:
  exportVar:
    rfg: ''
    MOTIF_BROKER_ENDPOINT: ''
    COUCH_ENDPOINT: ''

  modules: ["crispr-prod/3.0.0"]
  jobProfile: "crispr-dev"
  script: "computeAll.sh"
  sysSettingsKey: "crispr-dev"

specificGene:
  exportVar:
    blastdb: ''
    rfg: ''
    MOTIF_BROKER_ENDPOINT: ''
    COUCH_ENDPOINT: ''

  modules: ["crispr-prod/3.0.0", "blast+"]
  jobProfile: "crispr-dev"
  script: "computeSpecific.sh"
  sysSettingsKey: "crispr-dev"
