job-manager:
  address: "####"
  port: 0000
  scriptRoot: '####'

db:
  couchDB:
    connect:
      user: '####'
      password: '####'
      host: '####'
      port: 0000
    
    maxi_tree:
      doc: '####'
      database: '####'
    taxon:
      name: '####'
    genome:
      name: '####'

  motif-broker:
    host: '####'
    port: 0000

allGenomes:
  exportVar:
    rfg: '####'

  modules: ["crispr-prod/3.0.0"]
  jobProfile: "ws2-short"
  script: "crispr_workflow.sh"
  sysSettingsKey: "ws2-dev-cstb"

specificGene:
  exportVar:
    blastdb: '####'
    rfg: '####'

  modules: ["crispr-prod/3.0.0", "blast+"]
  jobProfile: "ws2-cstb"
  script: "crispr_workflow_specific.sh"
  sysSettingsKey: "ws2-short"
