job-manager:
  address: "192.168.118.202"
  port: 1235
  scriptRoot: '/data/www_dev/cstb/lib/cstb2-server/scripts'

db:
  couchDB:
    connect:
      user: 'cstb_agent'
      password: '8n9m4zY2kZtePvP'
      host: 'arwen-cdb.ibcp.fr'
      port: 5984
    
    maxi_tree:
      doc: 'maxi_tree'
      database: 'rc03_tree'
    taxon:
      name: 'taxon_db'
    genome:
      name: 'genome_db'

  motif-broker:
    host: 'localhost'
    port: 1236

allGenomes:
  exportVar:
    rfg: '/data/databases/cstb/rc03/index'

  modules: ["crispr-prod/3.0.0"]
  jobProfile: "ws2-short"
  script: "computeAll.sh"
  sysSettingsKey: "ws2-dev-cstb"

specificGene:
  exportVar:
    blastdb: '/data/databases/cstb/rc03/blast/blast'
    rfg: '/data/databases/cstb/rc03/index'

  modules: ["crispr-prod/3.0.0", "blast+"]
  jobProfile: "ws2-cstb"
  script: "computeSpecific.sh"
  sysSettingsKey: "ws2-short"
