job-manager:
  host: 'localhost'
  port: 1234

db:
  couchDB:
    url: 'localhost'
    port: 5984
    database: 'tree'
    user: 'admin'
    password: 'admin'

  sqlite:
    database: 'sqlite.db'

address: "127.0.0.1"
port: 1234